---
server:
  address: 'tcp://:9091'

log:
  level: 'debug'

totp:
  disable: false
  issuer: 'authelia.com'

authentication_backend:
  file:
    path: '/config/users_database.yml'

# https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: deny
  rules:
    - domain: 'auth.{{ env "MY_DOMAIN" }}'
      policy: bypass
    - domain: 'wg.{{ env "MY_DOMAIN" }}'
      policy: two_factor

session:
  cookies:
    - name: 'authelia_session'
      domain: '{{ env "MY_DOMAIN" }}'
      authelia_url: 'https://auth.{{ env "MY_DOMAIN" }}'
      expiration: '1 hour'
      inactivity: '5 minutes'

  redis:
    host: 'authelia_redis'
    port: 6379

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

telemetry:
  metrics:
    enabled: false
    address: 'tcp://:9959/metrics'
    buffers:
      read: 4096
      write: 4096
    timeouts:
      read: '6s'
      write: '6s'
      idle: '30s'

storage:
  local:
    path: '/config/db.sqlite3'

notifier:
  filesystem:
    filename: /config/notification.txt
