# yamllint disable rule:line-length
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  default:
    disabled: true
    displayname: "Default User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$lSP0ec0uIIswnMSQZYRCkQ$70o3Vw5F2MwojnPvXyAWxK40obuWjGFF5EXkU36VagI" # changeme
    email: authelia@authelia.com
