# yamllint disable rule:line-length
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  default:
    disabled: false
    displayname: "Default User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$4mtkFjXZySFwujuBgmLivQ$ya6+GHw+uCtitbfEjvju31NNZPtQAFSnhtRiGDTmIMA" # changeme
    email: authelia@authelia.com
